name: RPGLives
author: GloriousMeme
version: 3.0.0
api-version: "1.13"
description: "Gives multiple lives before dropping your items in specific worlds"
main: net.minequests.gloriousmeme.rpglives.RPGLives
softdepend: [PlaceholderAPI, Vault]
commands:
    lives:
    rpglives: